import { createHash } from "crypto";
import { NextRequest, NextResponse } from "next/server";

const GITHUB_OWNER = "crazyhansome2-bit";
const GITHUB_REPO = "myblog";
const GITHUB_API = "https://api.github.com";
const MAX_NAME_LENGTH = 32;
const MAX_CONTACT_LENGTH = 80;
const MAX_MESSAGE_LENGTH = 1000;
const RATE_WINDOW_MS = 10 * 60 * 1000;
const RATE_MAX_POSTS = 3;
const DUPLICATE_WINDOW_MS = 30 * 60 * 1000;

type GitHubIssue = {
  number: number;
  title: string;
};

type GitHubComment = {
  id: number;
  body: string;
  created_at: string;
  html_url: string;
  user?: {
    login?: string;
  };
};

type RateStore = {
  __linxCommentRate?: Map<string, number[]>;
  __linxCommentDuplicates?: Map<string, number>;
};

const stores = globalThis as typeof globalThis & RateStore;
stores.__linxCommentRate ||= new Map<string, number[]>();
stores.__linxCommentDuplicates ||= new Map<string, number>();

function pageHash(path: string) {
  return createHash("sha1").update(path).digest("hex").slice(0, 12);
}

function issueTitle(path: string) {
  return `[Comments] ${path} #${pageHash(path)}`;
}

function getToken() {
  return process.env.GITHUB_TOKEN || "";
}

function githubHeaders(token?: string) {
  return {
    Accept: "application/vnd.github+json",
    "Content-Type": "application/json",
    "X-GitHub-Api-Version": "2022-11-28",
    ...(token ? { Authorization: `Bearer ${token}` } : {}),
  };
}

async function githubFetch<T>(path: string, init: RequestInit = {}, token = getToken()) {
  const res = await fetch(`${GITHUB_API}${path}`, {
    ...init,
    headers: {
      ...githubHeaders(token),
      ...(init.headers || {}),
    },
  });

  if (!res.ok) {
    const text = await res.text();
    throw new Error(`GitHub request failed: ${res.status} ${text}`);
  }

  return res.json() as Promise<T>;
}

async function findIssue(path: string, token = getToken()) {
  const title = issueTitle(path);
  const issues = await githubFetch<GitHubIssue[]>(
    `/repos/${GITHUB_OWNER}/${GITHUB_REPO}/issues?state=all&per_page=100`,
    { method: "GET" },
    token,
  );

  return issues.find((issue) => issue.title === title) || null;
}

async function ensureIssue(path: string, token = getToken()) {
  const existingIssue = await findIssue(path, token);
  if (existingIssue) return existingIssue;

  return githubFetch<GitHubIssue>(
    `/repos/${GITHUB_OWNER}/${GITHUB_REPO}/issues`,
    {
      method: "POST",
      body: JSON.stringify({
        title: issueTitle(path),
        body: `Comment channel for ${path}\n\nGenerated by rogerlinx.com.`,
      }),
    },
    token,
  );
}

function cleanInput(value: unknown, maxLength: number) {
  return String(value || "")
    .replace(/[\u0000-\u001f\u007f-\u009f]/g, "")
    .replace(/\s{3,}/g, " ")
    .trim()
    .slice(0, maxLength);
}

function cleanMessage(value: unknown) {
  return String(value || "")
    .replace(/[\u0000-\u0008\u000b\u000c\u000e-\u001f\u007f-\u009f]/g, "")
    .replace(/@/g, "@ ")
    .trim()
    .slice(0, MAX_MESSAGE_LENGTH);
}

function normalizePath(value: unknown) {
  const path = cleanInput(value || "/", 120) || "/";
  if (!path.startsWith("/") || path.includes("://")) return "/";
  return path;
}

function publicCommentBody(body: string) {
  const match = body.match(/<!-- linx-comment-body -->([\s\S]*?)<!-- \/linx-comment-body -->/);
  return (match?.[1] || body).trim();
}

function publicCommentAuthor(body: string) {
  const match = body.match(/^Name: (.+)$/m);
  return match?.[1]?.trim() || "";
}

function clientKey(request: NextRequest) {
  const forwarded = request.headers.get("x-forwarded-for")?.split(",")[0]?.trim();
  return forwarded || request.headers.get("x-real-ip") || "unknown";
}

function isRateLimited(key: string) {
  const now = Date.now();
  const bucket = stores.__linxCommentRate?.get(key)?.filter((time) => now - time < RATE_WINDOW_MS) || [];
  if (bucket.length >= RATE_MAX_POSTS) {
    stores.__linxCommentRate?.set(key, bucket);
    return true;
  }

  bucket.push(now);
  stores.__linxCommentRate?.set(key, bucket);
  return false;
}

function isDuplicate(key: string, path: string, message: string) {
  const now = Date.now();
  const fingerprint = createHash("sha1").update(`${key}:${path}:${message}`).digest("hex");
  const lastSeen = stores.__linxCommentDuplicates?.get(fingerprint) || 0;

  if (now - lastSeen < DUPLICATE_WINDOW_MS) return true;

  stores.__linxCommentDuplicates?.set(fingerprint, now);
  return false;
}

function validateComment(name: string, contact: string, message: string) {
  const linkCount = (message.match(/https?:\/\//gi) || []).length;
  const repeatedChars = /(.)\1{24,}/.test(message);
  const hasScriptPayload = /<\s*script|javascript:|data:text\/html/i.test(message);

  if (!name || !message) return "Please fill in your name and message.";
  if (message.length < 2) return "Message is too short.";
  if (linkCount > 2) return "Too many links in one message.";
  if (repeatedChars) return "Message looks like repeated spam.";
  if (hasScriptPayload) return "Message contains unsafe content.";
  if (/https?:\/\//i.test(name + contact)) return "Please do not put links in name or contact.";

  return "";
}

export async function GET(request: NextRequest) {
  const token = getToken();
  const path = normalizePath(request.nextUrl.searchParams.get("path"));

  if (!token) {
    return NextResponse.json({ configured: false, comments: [] });
  }

  try {
    const issue = await findIssue(path, token);
    if (!issue) {
      return NextResponse.json({ configured: true, comments: [] });
    }

    const comments = await githubFetch<GitHubComment[]>(
      `/repos/${GITHUB_OWNER}/${GITHUB_REPO}/issues/${issue.number}/comments?per_page=100`,
      { method: "GET" },
      token,
    );

    return NextResponse.json({
      configured: true,
      comments: comments.map((comment) => ({
        id: comment.id,
        author: publicCommentAuthor(comment.body) || comment.user?.login || "Visitor",
        body: publicCommentBody(comment.body),
        createdAt: comment.created_at,
        url: comment.html_url,
      })),
    });
  } catch (error) {
    console.error("[api/comments] GET failed:", error);
    return NextResponse.json({ error: "Failed to load comments." }, { status: 500 });
  }
}

export async function POST(request: NextRequest) {
  let payload: Record<string, unknown>;

  try {
    payload = await request.json();
  } catch {
    return NextResponse.json({ error: "Invalid request body." }, { status: 400 });
  }

  if (cleanInput(payload.website, 120)) {
    return NextResponse.json({ ok: true });
  }

  const token = getToken();
  if (!token) {
    return NextResponse.json({ error: "Comment service is not configured." }, { status: 500 });
  }

  const key = clientKey(request);
  if (isRateLimited(key)) {
    return NextResponse.json(
      { error: "You are sending messages too quickly. Please try again later." },
      { status: 429 },
    );
  }

  try {
    const path = normalizePath(payload.path);
    const name = cleanInput(payload.name, MAX_NAME_LENGTH);
    const contact = cleanInput(payload.contact, MAX_CONTACT_LENGTH);
    const message = cleanMessage(payload.message);
    const validationError = validateComment(name, contact, message);

    if (validationError) {
      return NextResponse.json({ error: validationError }, { status: 400 });
    }

    if (isDuplicate(key, path, message)) {
      return NextResponse.json(
        { error: "This message was already sent. Please do not submit it repeatedly." },
        { status: 409 },
      );
    }

    const issue = await ensureIssue(path, token);
    const body = [
      `Name: ${name}`,
      contact ? `Contact: ${contact}` : "",
      `Page: ${path}`,
      "",
      "<!-- linx-comment-body -->",
      message,
      "<!-- /linx-comment-body -->",
    ].filter(Boolean).join("\n");

    const comment = await githubFetch<GitHubComment>(
      `/repos/${GITHUB_OWNER}/${GITHUB_REPO}/issues/${issue.number}/comments`,
      {
        method: "POST",
        body: JSON.stringify({ body }),
      },
      token,
    );

    return NextResponse.json({
      ok: true,
      comment: {
        id: comment.id,
        author: name,
        body: message,
        createdAt: comment.created_at,
        url: comment.html_url,
      },
    });
  } catch (error) {
    console.error("[api/comments] POST failed:", error);
    return NextResponse.json({ error: "Failed to send comment." }, { status: 500 });
  }
}
